source 'http://rubygems.org'

# ruby "2.1.1"

gem 'rails', '4.1.11'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

group :test, :development do
  gem "sqlite3"
  gem "pg"
  gem "byebug"
  gem "bullet"
end

group :production do
  gem "pg"
  gem 'therubyracer', :platforms => :ruby
end

# comment ES
# Gems used only for assets and not required
# in production environments by default.


# RAILS 4 thingy
gem 'protected_attributes'
gem 'rails-observers'
gem 'actionpack-page_caching'
gem 'actionpack-action_caching'
gem 'activerecord-deprecated_finders'

group :production do
  gem 'rails_12factor'
end


group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'
  gem 'angularjs-rails'
  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  gem 'uglifier'
end

gem 'jquery-rails'


# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
#
gem 'bson_ext'
#gem 'mongo'
#gem 'mongoid'

gem "pusher"

gem "fb_graph"
gem "twitter"
gem 'delayed_job_active_record'
gem 'delayed_job_web'

gem "thin"
gem "em-http-request"

gem "redis"

group :production do
  gem "newrelic_rpm"
end


#gem 'sidekiq'

#gem "execjs"
#gem "therubyracer"

gem "devise", "~> 3.1.1"

#gem 'carrierwave'
gem "fog"
gem 'carrierwave_direct'

gem "aws-sdk", "< 2.0"
gem 'rack-pjax'
# gem 'angular-rails-templates'

group :development, :test do
  gem 'guard-rspec', require: false
  gem 'rspec-rails'
  gem 'rspec'
  gem "rspec-mocks"
  gem 'rspec-activemodel-mocks'
#    gem 'factory_girl_rails', :require => false
  gem 'factory_girl_rails'
  gem "shoulda-matchers"
  gem "spork"
  gem 'pusher-fake'
#gem 'jasmine-rails'
#    gem 'jasmine'
  gem 'faker'
end

# group :development do
#   gem 'meta_request'
#   gem 'capistrano'
#   gem 'capistrano-unicorn', :git => 'https://github.com/sosedoff/capistrano-unicorn.git', :branch => 'master', :require => false
#   gem 'rvm-capistrano'
# end

group :test do
  gem 'capybara'
  gem 'launchy'
end
gem "unicorn"

#gem 'rack-mini-profiler'

gem "gibbon"

gem "figaro"


#gem 'activeadmin'
#gem "meta_search"

gem "hirb"

gem "htmlentities", "~> 4.3.1"

gem 'seed_dump'

#gem 'textacular'

gem 'sunspot_rails'
gem 'sunspot_solr'
#gem 'tire'
#gem 'progress_bar'


gem 'daemons'
gem "twitter-text"

gem "rmagick", require: false

gem 'rack-cache'
gem 'dalli'
gem "memcachier"


gem "bunny"

gem "parse-ruby-client"


gem 'rack-cors', :require => 'rack/cors'
gem 'puma'

gem 'chronic'

# gem "spring", group: :development

gem 'simplecov', :require => false, :group => :test
gem 'braintree'

group :development, :test do
    gem 'railroady'
end

# ---
# Curb - Libcurl bindings for Ruby
# https://github.com/taf2/curb
gem 'curb'

# ---
# Geocoder - Geocoder is a complete geocoding solution for Ruby
# https://github.com/alexreisner/geocoder
gem 'geocoder'

# ---
# Geo Location - Easily geo-locate your users using their IP address via hostip.info or maxmind.com.
# https://github.com/chrisyour/geo_location
gem 'geo_location'


# ---
# Geokit - Official Geokit Gem. Geokit gem provides geocoding and distance/heading calculations. Pair with the geokit-rails plugin for full-fledged location-based app functionality.
# https://github.com/geokit/geokit
gem 'geokit'

# ---
# Browser - Do some browser detection with Ruby
# https://github.com/fnando/browser
gem 'browser'
gem 'puma_worker_killer'
gem 'httparty'
